### ISSUE TITLE
Bug: Android 12

### ISSUE THREAD

**Issue by jelllyam** [kadiraydinli/react-native-system-navigation-bar#46]
Not working with top notch. The status bar blank space still exist even I added in <View> style Flex:1

**Comment by kadiraydinli** [comment]
Hi @jelllyam, can you share sample code and screenshot so I can better understand the problem?

**Comment by jelllyam** [comment]
This is the  [https://github.com/kadiraydinli/react-native-system-navigation-bar/tree/master/example](example) that i'm using.


https://user-images.githubusercontent.com/11318868/233749903-373172c0-dbe5-429a-b6f1-42bea9a2f997.mp4

**Comment by kadiraydinli** [comment]
I think your phone has a notch. If so, I think the problem will be solved when you add the code below to `/android/app/src/main/res/values/styles.xml` and try again.

```xml
<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
```

After adding the code, the estimated image of the file will look like this.

```xml
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>
</resources>
```

Check out the link below for more information on this code;
https://developer.android.com/develop/ui/views/layout/display-cutout

I recommend that you be careful when using this code. I am not sure if it will cause the content to shift out of the safe area on some screens. But I don't think there will be a problem if you use `SafeAreaView` on all the screens in your application.

**Comment by jelllyam** [comment]
> I think your phone has a notch. If so, I think the problem will be solved when you add the code below to `/android/app/src/main/res/values/styles.xml` and try again.
> 
> ```
> <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
> ```
> 
> After adding the code, the estimated image of the file will look like this.
> 
> ```
> <resources>
>     <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>         <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
>         <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
>     </style>
> </resources>
> ```
> 
> Check out the link below for more information on this code; https://developer.android.com/develop/ui/views/layout/display-cutout
> 
> I recommend that you be careful when using this code. I am not sure if it will cause the content to shift out of the safe area on some screens. But I don't think there will be a problem if you use `SafeAreaView` on all the screens in your application.

It's working but the problem is when I rotate to landscape, the side still has blank space. 

![Screenshot_20230423-221457](https://user-images.githubusercontent.com/11318868/233845013-66b17dac-b66b-44db-9174-bf0d08bc26f9.jpg)

**Comment by kadiraydinli** [comment]
@jelllyam I have released a new version that fixes this issue. Can you check again on the latest version?

**Comment by kadiraydinli** [comment]
I think your problem is solved. That's why I'm closing this issue. If your problem persists, feel free to reopen the issue.

**Comment by testkil** [comment]
@kadiraydinli I still have the issue :/ (red is just hidden)

![image](https://github.com/kadiraydinli/react-native-system-navigation-bar/assets/49737034/95a421a5-928d-40f5-8010-abe5ba19cb2e)
